---
title: "module4"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{module4}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(asta)
library(dplyr)
library(ggplot2)
```



```{r}
model_lineaireS_tab <- function(input_data, var_expliquee, var_explicative, constante){
  
  if (constante == TRUE) {
  a <- paste0(var_expliquee, "~ 0 + ", var_explicative)
   model <- lm(as.formula(a), data = input_data)
  result <- summary(model)
  result}
  else {  a <- paste0(var_expliquee, "~", var_explicative)
   model <- lm(as.formula(a), data = input_data)
  result <- summary(model)
  result}
}

model_lineaireS_tab(grandile, "REV_DISPONIBLE", "PATRIMOINE")
```

```{r}
model_lineaireS_plot <- function(input_data, var_expliquee, var_explicative, constante){
  
    if (constante == TRUE) { a <- paste0(var_expliquee, "~ 0 + ", var_explicative)
  model <- lm(as.formula(a), data = input_data)
  result <- summary(model)
  
  a <- input_data %>% ggplot(aes(x = .data[[var_explicative]],y = .data[[var_expliquee]])) + 
    geom_point(alpha=0.2,size=1,color="darkblue") + 
    theme_minimal() +
    geom_smooth(method="lm",color="red")
  
  
  coeff=coefficients(model)
  a + geom_abline(intercept = 0, slope = coeff[1])}
  
  else {
  
  a <- paste0(var_expliquee, "~", var_explicative)
  model <- lm(as.formula(a), data = input_data)
  result <- summary(model)
  
  a <- input_data %>% ggplot(aes(x = .data[[var_explicative]],y = .data[[var_expliquee]])) + 
    geom_point(alpha=0.2,size=1,color="darkblue") + 
    theme_minimal() +
    geom_smooth(method="lm",color="red")
  
  
  coeff=coefficients(model)
  a + geom_abline(intercept = coeff[1], slope = coeff[2])}
  }

model_lineaireS_plot(grandile, "REV_DISPONIBLE", "PATRIMOINE")

```



```{r}
model_lineaireM_tab <- function(input_data, var_expliquee, var_explicatives){
   a <- paste0(var_expliquee, "~", paste0(var_explicatives, collapse = "+"))
  model <- lm(as.formula(a), data = input_data)
  result <- summary(model)
  result
}

model_lineaireM_tab(iris, "Petal.Length", c("Sepal.Length", "Petal.Width", "Sepal.Width"))
```

