---
title: "module5"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{module5}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(asta)
library(datasets)
library(lubridate)
library(ggplot2)
library(dygraphs)
```

# Analyse de la série

Dans cette onglet, il faut d'abord choisir une série parmi celles proposées dans le menu déroulant : 
- Airpassengers (package datasets)
- Taux d'occupation dans l'hotellerie
- Nombre de visiteurs d'un musée


```{r}
airpass_ts <- AirPassengers
airpass_ts

#Fonction qui transforme une ts en dataframe
ts_to_dt <- function(serie_ts,date_debut,periode,taille){
  data.frame(
  date=seq(date_debut, by = periode, length.out = taille),
  as.data.frame(serie_ts)
  )
}

#Exemple
airpass_dt <- ts_to_dt(airpass_ts,
         date_debut = my("01/1949"),
         periode = "month",
         taille = 144)
airpass_dt

```

Création d'une fonction qui récupère le nom de la série au format caractère pour l'afficher au format dygraph

```{r}
plot_ts <- function(serie_ts){
  plot.ts(eval(parse(text = serie_ts)))
}

dygraph_ts <- function(serie_ts){
  dygraph(eval(parse(text = serie_ts)))
}

#Exemple
plot_ts("airpass_ts")
dygraph_ts("airpass_ts")

plot_dt <- function(dt){
  ggplot(dt)+
    aes(x = date,y=x) +
    geom_line()
}
#Exemple
plot_dt(airpass_dt)

```



