---
title: "module2"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{module2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup, warning=FALSE, message=FALSE}
library(asta)
library(sampling)
library(dplyr)
library(questionr)
```


1. fonction d'importation -----
```{r}
# file_grandile_m2 <- function (input_data) {
#   data_grandile_m2 <-
#     readRDS(file = system.file(input_data, package = "asta"))
#   data_grandile_m2
# }
# 
# (file_grandile_m2("Grandile.RDS"))
# (file_grandile_m2("Grandile_apur.RDS"))
# (file_grandile_m2("Grandile_brut.RDS"))
# (file_grandile_m2("Grandile_redress.RDS"))
```

2. Fonction de tirage aleatoire simple -----
```{r}

tirage_sas_m2 <- function(input_data, taille_sas) {
  echantillon_sas <-
    input_data[sample(1:nrow(input_data), taille_sas),]
  echantillon_sas
}

 tirage_sas_m2(grandile, 12)
```

3. Fonction de tirage stratifie -----
```{r}
tirage_strat_m2 <- function(input_data, taille_strat, var_strat) {
  tab <- input_data %>%   select(.data[[var_strat]])
  
  v <- table(tab)
  
  x <- v / nrow(input_data)
  
  y <- x * taille_strat
  
  base_echantillon_strat <-
    input_data %>% arrange(var_strat)
  
  s = strata(
    base_echantillon_strat,
    stratanames =
      var_strat,
    size = y,
    method = "srswor"
  )
  echantillon_strat <- getdata(base_echantillon_strat, s)
  
}

tirage_strat_m2(grandile, 400, "DIPL")

```


4. Fonction de tirage a 2 degres -----
```{r}
tirage_degres_m2 <-
  function(input_data,
           taille_UP,
           taille_tot,
           var_degres) {
    UP <-
      file_grandile_m2(input_data) %>% group_by(.data[[var_degres]]) %>%
      summarise(Effectifs = n()) %>% select(.data[[var_degres]])
    
    sond1 <-
      UP[sample(1:nrow(UP), taille_UP), ] %>% mutate(ECH = "1")  %>%
      right_join(file_grandile_m2(input_data), by = var_degres) %>%
      filter(ECH == "1")
    
    sond2 <- tirage_strat_m2(input_data, taille_tot, var_degres)
    sond2
  }


# tirage_degres_m2("Grandile.RDS", 3, 500, "DIPL")

```

5. Fonction de tirage en grappe -----
```{r}
tirage_grappe_m2 <- function (input_data, taille_grappe, var_grappe) {
  UP <-
    file_grandile_m2(input_data) %>% group_by(.data[[var_grappe]]) %>%
    summarise(Effectifs = n()) %>% select(.data[[var_grappe]])
  
  sond1 <-
    UP[sample(1:nrow(UP), taille_grappe), ] %>% mutate(ECH = "1")  %>%
    right_join(file_grandile_m2(input_data), by = var_grappe) %>%
    filter(ECH == "1")
  
}

# tirage_grappe_m2("Grandile.RDS", 2, "DIPL")
```


6.Fonction de box plot pour les tirages -----
```{r}
boxplot_tirage_m2 <- function(input_data, var_plot) {
  ggplot(file_grandile_m2(input_data)) +
    geom_boxplot(aes(y = .data[[var_plot]]),  color = "blue") + scale_x_discrete() + 
    ylim (min = 9800, max = 116800) +
    labs(caption = "Source : Cefil 2021")
  
}

# boxplot_tirage_m2("Grandile.RDS", "PATRIMOINE")
```

7. Fonction de creation d'une base apuree -----
```{r}
data_apur_m2 <- function(input_data, min_apur, max_apur, var_apur) {
  apur <- file_grandile_m2(input_data) %>%
    filter(.data[[var_apur]] > min_apur) %>%
    filter(.data[[var_apur]] < max_apur) %>%
    arrange(.data[[var_apur]]) %>% mutate(numero = row_number())
}
  
# data_apur_m2("Grandile_apur.RDS",100, 500, var_apur = "SUPERF_LOG")
```

8. Fonction de plot simple sur base apuree -----
```{r}
plot_apur_m2 <-
  function (input_data,
            min_apur2,
            max_apur2,
            var_apur2) {
    ggplot(data_apur_m2(input_data,
                        min_apur2,
                        max_apur2,
                        var_apur2)) +
      geom_point(aes(x = numero, y = .data[[var_apur2]]),) +
      theme_light() + labs(x = NULL)
    
  }

# plot_apur_m2("Grandile_apur.RDS", 1, 500, var_apur2 =  "SUPERF_LOG")
```


```{r}

cramer_m2 <- function(data,varquali1,varquali2){
  a <- table(data$varquali1,data$varquali2)
  cramer.v(a)
  }

cramer_m2( data=grandile_redress,varquali1= "REPONDANT_C",varquali2 = "ACT")


```

